  name: Copy files to another repository
  on:
    push:
      branches-ignore:
        - main

  jobs:
      deploy:
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Copy files
          uses: lubu12/copy-files-to-repository@v1
          env:
            API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
            BRANCH_NAME: ${{ github.ref }}
          with:
            source-files: '.'
            destination-username: "fegtoken-labs"
            destination-repository: "SD-assets"
            destination-branch: main
            destination-directory: "${{ github.ref }}/"
            commit-email: "fegfilip@gmail.com"
            commit-username: "FEGfilip"
