  name: Copy files to another repository
  on:
    push:
      branches-ignore:
        - main

  jobs:
      deploy:
        runs-on: ubuntu-latest
    
        steps:
        - name: Copy files
          uses: lubu12/copy-files-to-repository@v1
          env:
            API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
            BRANCH_NAME: ${{ github.ref }}
            REPO: ${{ github.repository }}
          with:
            source-files: '/'
            destination-username: 'workflow actions'
            destination-repository: '$REPO'
            destination-branch: 'main'
            destination-directory: '$BRANCH_NAME'
            commit-email: 'workflow@github.com'
