name: Deploy to GitHub Pages

on:
  push:
    branches-ignore:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
        
        # Configure git
        git config --global user.email "fegfilip@gmail.com"
        git config --global user.name "FEGfilip"
        
        # Fetch and checkout the gh-pages branch or create it if it doesn't exist
        git fetch origin gh-pages
        git checkout gh-pages || git checkout --orphan gh-pages
        
        # Create the target directory for the current branch
        mkdir -p $BRANCH_NAME
        
        # Use rsync to copy the content to the target directory
        rsync -av --progress . $BRANCH_NAME --exclude .git --exclude $BRANCH_NAME
        
        # Add and commit the changes
        git add $BRANCH_NAME/
        git commit -m "Deploy $BRANCH_NAME" || echo "No changes to commit"
        
        # Push the changes to the gh-pages branch
        git push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" gh-pages
